---
test_docker:
    token: some_secret 
    #host: 127.0.0.1
    host: test
    port: 8899
    swagger: test_docker 
    
validator:
    #host: 127.0.0.1
    host: validator
    port: 8899
    swagger: validator
...
